# Generated by Django 4.2.6 on 2023-11-17 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cycling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GameTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cycling.game')),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('real_team', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RiderGameTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cycling.gameteam')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cycling.rider')),
            ],
        ),
        migrations.CreateModel(
            name='RiderStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('shirt_points', models.IntegerField()),
                ('total_points', models.IntegerField()),
                ('cumulative_total_points', models.IntegerField()),
                ('position', models.IntegerField()),
                ('shirts', models.JSONField()),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cycling.rider')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('is_klassieker', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StageTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cycling.stage')),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='renners',
        ),
        migrations.RemoveField(
            model_name='team',
            name='reserves',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_name',
        ),
        migrations.AddField(
            model_name='tour',
            name='is_klassieker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tour',
            name='url',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Renner',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AddField(
            model_name='stagetour',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cycling.tour'),
        ),
        migrations.AddField(
            model_name='riderstage',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cycling.stage'),
        ),
        migrations.AddField(
            model_name='game',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cycling.tour'),
        ),
    ]
