# Generated by Django 4.2.6 on 2023-11-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cycling', '0002_game_gameteam_rider_ridergameteam_riderstage_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridergameteam',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sub', 'Substitute'), ('non_active', 'Non Active')], default='non_active', max_length=10),
        ),
        migrations.AddField(
            model_name='riderstage',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sub', 'Substitute'), ('non_active', 'Non Active')], default='non_active', max_length=10),
        ),
        migrations.AddField(
            model_name='stage',
            name='stage_type',
            field=models.CharField(choices=[('not_defined', 'Not defined'), ('bergrit', 'Bergrit'), ('tijdrit', 'Tijdrit'), ('heuvels', 'Heuvels'), ('teamtijdrit', 'Teamtijdrit'), ('finish_op_berg', 'Finish op Berg')], default='non_defined', max_length=20),
        ),
        migrations.AddField(
            model_name='stagetour',
            name='stage_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
